version: "3"
networks:
  favorite:
    driver: bridge
services:
  backend:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - favorite
    command: /bin/sh -c "node_modules/.bin/nodemon --exec npm run dev"
  mongo:
    image: mongo:latest
    container_name: "mongo"
    environment:
      - MONGODB_USER="zxckjasdqwuxzckjna"
      - MONGODB_PASS="alkasnd@#@!@#asdkn123"
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./backend/data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      - favorite
  front:
    container_name: front
    working_dir: /app
    build:
      context: ./front
      dockerfile: Dockerfile
    # volumes:
    #   - "./front:/app"
    #   - "/app/node_modules"
    volumes:
      - "./front:/app/front"
    command: /bin/sh -c "cd front && npm run dev"
    networks:
      - favorite
    depends_on:
      - backend
    ports:
      - "8080:3000"
    # environment:
    #   - NODE_ENV=development
volumes:
  mongodata:
    external: false
